# Generated by Django 4.1.1 on 2023-09-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_absence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
